services:
  api:
    build:
      context: .
      dockerfile: .docker/api/dev/Dockerfile
    environment:
      - PORT
      - REDIS_HOST
      - REDIS_PORT
      - DATABASE_URL
      - ACCESS_TOKEN_SECRET
      - ACCESS_TOKEN_EXPIRATION
      - REFRESH_TOKEN_SECRET
      - REFRESH_TOKEN_EXPIRATION
      - STRIPE_SECRET_KEY
      - STRIPE_CURRENCY
      - POSTGRES_PORT
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 3000:3000
    networks:
      - db_network
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    networks:
      - db_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - db_network
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - db_network
    ports:
      - "5050:80"
    depends_on:
      - postgres

networks:
  db_network:

volumes:
  postgres_db: